### ISSUE TITLE
VS Code formatting handlebars containing `<!doctype html>` not working

### ISSUE THREAD

**Issue by leifhanack** [mfeckie/handlebars-formatter#25]
Hi there, first of all, thank you for your vs code extension. 

I ran into a strange problem where you hopefully can help.

I have a file `foo.hbs` with

```
<!doctype html>
<head>
  <meta charset="UTF-8" />
                 <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link
    rel="stylesheet"
    type="text/css"
    href="{{asset "built/tailwind.css"}}"
  />
</head>
                <body>
  <h1>foo</h1>
</body>
```

Formatting this file results in nothing else than: 

```
{{asset "built/tailwind.css"}}
```

In another file with more content, the content remains as is, but isn't formatted. 

As soon as I remove the `<!doctype html>` line, the formatting is working again and results in:

```
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link
    rel="stylesheet"
    type="text/css"
    href="{{asset "built/tailwind.css"}}"
  />
</head>
<body>
  <h1></h1>
</body>
```

Any idea what I'm doing wrong?

My settings contains: 
```
  "[handlebars]": {
    "editor.defaultFormatter": "mfeckies.handlebars-formatter"
  },
```

Thanks a lot, Leif

**Comment by mfeckie** [comment]
Hey @leifhanack, this looks like an issue with the underlying way in which the glimmer parser operates in prettier.

I can replicate the problem on the REPL here https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAEwmGBPABzgAIALGAWwBsA+AHSlVLgENN6pjjUK4YXiYUiwBOAZz4BeOiACqAFQBiAWgAcM4gHoOXXXv26efAVBa9pIAG4BLOAHcCEETA2RYCGBbvXMMUpMw4GzA4ZW9fUgAaYmsoaxhrFiplMTAkuEkARgA6AAYNbQYuVCpYgGsi3RE4KgsxfCo4MWY+GUqufCILeAAPGE0wMTE2zl1SaoAzC2BgFiG+YhkAIwBXayp+-nXvKExsweGQAF8jka5Cxk1mNh0DO+KliEw8W6ZMmgmICFQr94Yfx7PGggSIgCAEBLQMTIUCiEQQOwABVECGhKCSdhYeGhoKWIhYYDKfAAygQCbEAObIGAiFZwUFwChLOCYQKYAAyLCgFJWLApcEUTgoLBgCW5yBALBWMAgIJA5GoAHVSPEmmSQsTUfFrDZ8BKDnLYhJnIj8RThcgJkkJKCAFZiHoAIXxhJJZjg7NicEt1vpIHtPWJlMaAEUVhB4D6qDaQGTxHARBKKaUKLxE6CCCJYjBFT4-MhVLkM-CJIr8QQJZmmgnLN7QQBHcPwU3gtGSsTKKBwFksuXVRvWaqmvkWpBW6N+iQUazU2mT4NwMMR71j32g-hLXMRZAAJnX+PWlIAwhBUywJU0AKxylYSeQsJZo8cxyx0gCSuw8xLAWYhAEFdmJBoV2fOATiAA

Because this is related to prettier itself, rather than this extension, I'd recommend sharing with them at https://github.com/prettier/prettier

It's probably also worth doing some thinking about whether this behaviour is expected as I don't believe that glimmer templates would normally contain full `<html>` and `DOCTYPE` lines.
