### ISSUE TITLE
Indent with tabs instead of spaces

### ISSUE THREAD

**Issue by samrichca** [mfeckie/handlebars-formatter#3]
Is it possible to use this with tabs instead of spaces?

I've tried removing all other prettier/beautify plugins and changing all my VSCode settings to tabs. When I format with this plug it changes my spaces to tabs.

Thanks, it's a great plugin otherwise!

**Comment by mfeckie** [comment]
@samrichca 	This extension uses `prettier` under the hood.  Do you have a `.prettierrc` file in your project?

Prettier does allow you to set tabs instead of spaces, so that may be an option https://prettier.io/docs/en/options.html#tabs

There's nothing specific to this extension that forces spaces, it's all delegated to prettier.
